### PR TITLE
Bug 2049073: Fix proxy injection

### PR DESCRIPTION
**Pull request by jsafrane**
By adding `CSIConfigObserverController` that adds proxy config into `ClusterCSIDriver.Spec.ObservedConfig`. There are already proxy hooks that add the proxy from `ObservedConfig` to the driver Deployment + DaemonSet.

### CODE REVIEW

**Comment by jsafrane** [comment]
cc @openshift/storage

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Pull request merged**
