### PR TITLE
[release-4.13] OCPBUGS-16250: Add management workloads annotations

### PR DESCRIPTION
**Pull request by Phaow**
This is a manual cherry-pick of [#66](https://github.com/openshift/aws-efs-csi-driver-operator/pull/66) , fix the OCPBUGS-16250.

### CODE REVIEW

**Comment by Phaow** [comment]
The `ci/prow/operator-e2e-extended` job is picked by bot mistake, it should only be available on 4.14+.

**Comment by eggfoobar** [comment]
/lgtm

Validated the daemonset and deployment had the annotations applied.

**Comment by jsafrane** [comment]
/approve
?

**Comment by Phaow** [comment]
Hello @jsafrane , it's a bit strange the ci/prow/operator-e2e-extended job is picked by bot mistake, it should only be available on 4.14+ and  it is`optional`, the merge bot seems treat it as a required job. Could you please help override it or refresh the test jobs list when you get a chance? Thanks!

**Pull request merged**
