### PR TITLE
Bug 2038934: Add custom CA bundle support

### PR DESCRIPTION
**Pull request by jsafrane**
Add support for proxy CA bundles.
Bump library-go and other dependencies (e.g. Kubernetes libs) and update the operator to it.
cc @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
/hold
I can see some panics in e2e tests

**Comment by jsafrane** [comment]
/retest
installation failed

**Review by bertinatto — COMMENTED** [review]
/lgtm

**Comment by bertinatto** [comment]
@jsafrane changes LGTM. I'll let you remove the `hold` tag in case there's anything else you want to check before merging.

**Pull request merged**
