### PR TITLE
STOR-1402, STOR-1453: update libraries and specify TLS_MIN_VERSION

### PR DESCRIPTION
**Pull request by dobsonj**
- [STOR-1402](https://issues.redhat.com//browse/STOR-1402): Chore: update libraries in all operators [4.15]
- [STOR-1453](https://issues.redhat.com//browse/STOR-1453): Specify TLS_MIN_VERSION in kube-rbac-proxy

/cc @openshift/storage

### CODE REVIEW

**Comment by jsafrane** [comment]
I don't like CI failures here:

`Back-off restarting failed container provisioner-kube-rbac-proxy in pod aws-efs-csi-driver-controller-54cd9c5d44-2vlss_openshift-cluster-csi-drivers(4fa1b3c3-1dbd-4037-a349-6195468ae352)] happened 25 times`

And the provisioner-kube-rbac-proxy logs:

```
... err="TLS version invalid: unknown tls version \"${TLS_MIN_VERSION}\""
```

**Comment by dobsonj** [comment]
`
W1120 22:46:29.878503       1 reflector.go:535] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: failed to list *v1.APIServer: apiservers.config.openshift.io is forbidden: User "system:serviceaccount:openshift-cluster-csi-drivers:aws-efs-csi-driver-operator" cannot list resource "apiservers" in API group "config.openshift.io" at the cluster scope
E1120 22:46:29.878528       1 reflector.go:147] k8s.io/client-go@v0.28.4/tools/cache/reflector.go:229: Failed to watch *v1.APIServer: failed to list *v1.APIServer: apiservers.config.openshift.io is forbidden: User "system:serviceaccount:openshift-cluster-csi-drivers:aws-efs-csi-driver-operator" cannot list resource "apiservers" in API group "config.openshift.io" at the cluster scope
`

**Comment by duanwei33** [comment]
Test with open PR:
1) TLS profile in cm/config:
```
$ oc -n openshift-apiserver get cm config -o jsonpath="{.data.config\.yaml}" | jq .servingInfo
{
  "bindNetwork": "tcp",
  "cipherSuites": [
    "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
    "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
  ],
  "minTLSVersion": "VersionTLS12"
}
```

2) TLS profile in clustercsidriver
```
$ oc get clustercsidriver -o json efs.csi.aws.com | jq .spec.observedConfig.targetcsiconfig.servingInfo
{
  "cipherSuites": [
    "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
    "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256"
  ],
  "minTLSVersion": "VersionTLS12"
}
```

3) TLS profile in csi driver controller:
```
$ oc -n openshift-cluster-csi-drivers get deployment aws-efs-csi-driver-controller -o json | jq .spec.template.spec.containers[] | jq 'select(.name | match(".*kube-rbac-proxy.*")) | {container: .name, arg: .args}'
{
  "container": "provisioner-kube-rbac-proxy",
  "arg": [
    "--secure-listen-address=0.0.0.0:9212",
    "--upstream=http://127.0.0.1:8212/",
    "--tls-cert-file=/etc/tls/private/tls.crt",
    "--tls-private-key-file=/etc/tls/private/tls.key",
    "--tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
    "--tls-min-version=VersionTLS12",
    "--logtostderr=true"
  ]
}
```

4) TLS profile is used in container:
```
The container provisioner-kube-rbac-proxy in pod aws-efs-csi-driver-controller-5db9cd94b6-f9jhh:
nobody         1       0  0 06:57 ?        00:00:00 /usr/bin/kube-rbac-proxy --secure-listen-address=0.0.0.0:9212 --upstream=http://127.0.0.1:8212/ --tls-cert-file=/etc/tls/private/tls.crt --tls-private-key-file=/etc/tls/private/tls.key --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 --tls-min-version=VersionTLS12 --logtostderr=true
```

**Pull request merged**
